### PR TITLE
Instance mocks should receive a copy of default expectations

### PR DESCRIPTION
**Pull request by davedevelopment**

### CODE REVIEW

**Comment by davedevelopment** [comment]
Hmm, might need some more work on this

**Comment by aik099** [comment]
What are these `default expectations` and what is the issue solved by this PR actually?

**Comment by davedevelopment** [comment]
Default expectations are ones that can be overridden, so they're almost secondary expectations. When we check to see if we were expecting something, we loop over the normal expectations first, then over the default expectations.

**Comment by aik099** [comment]
Ah, I thought that default expectations are ones, that are added first and when you add `->byDefault()` the expectation is added to the top of the expectation list instead of to the end as happens usually.

**Pull request merged**
