### PR TITLE
CS fixes to PSR-2 level

### PR DESCRIPTION
**Pull request by padraic**

### CODE REVIEW

**Comment by aik099** [comment]
I hope you haven't done all these fixes by hand. There is PHP_CodeSniffer 2.x versions, that not only reports issues, but also can fix them. And there is PHP-CS-Fixer.

**Comment by GrahamCampbell** [comment]
And https://styleci.io/ launches soon. :)

**Comment by padraic** [comment]
@aik099 @GrahamCampbell php-cs-fixer :laughing: 

@GrahamCampbell Very nice! I'll be sure to check it out when it launches.

**Comment by GrahamCampbell** [comment]
We're using php-cs-fixer under the hood, so we'll respect any .php_cs file with your config in.

**Comment by GrahamCampbell** [comment]
@padraic Just to let you know that I've launched https://styleci.io/ now. :)

**Comment by aik099** [comment]
That's great news. Some more docs wouldn't hurt in there. I've tried to use it and the only thing I was able to do is to get list of my repos and enable StyleCI on one of them. I have no idea what will happen and where do I specify standard to be checked. Actually I have no idea what that website does in general.

**Pull request merged**
