### PR TITLE
Added MockeryPHPUnitIntegration.

### PR DESCRIPTION
**Pull request by Bilge**
Re: #424.

### CODE REVIEW

**Comment by padraic** [comment]
@Bilge Could we impose on you to include something about this in the docs also? :)

**Comment by Bilge** [comment]
I don't think so, bro. I'd love to but I don't have that kind of time.

**Comment by padraic** [comment]
@Bilge No problem.

@davedevelopment I'll let you merge and then you can ping me to write some docs.

**Comment by davedevelopment** [comment]
Thanks!

**Comment by fhinkel** [comment]
This breaks the 5.3 build (for obvious reasons).

**Comment by aik099** [comment]
From build log I don't get which test calls the trait. I guess it's PHPUnit itself scans all files and hits the error.

**Comment by aik099** [comment]
It seems, that PHUnit tried to build coverage report and since file with a trait is within whitelisted folder it includes it and gets an error.

Maybe we should update `phpunit.xml` to exclude file with trait from ones, requiring coverage checks.

**Comment by padraic** [comment]
There's an easy fix for that ;).

I tried a blacklist, but no joy. Would need to remove the uncoveredfiles attribute on the whitelist I think.

**Comment by padraic** [comment]
@fhinkel @aik099 Fixed in current master. Just excluded it from whitelist for now.

**Comment by aik099** [comment]
Thanks.

Travis badge still red, but this is due HHVM eval problem, which suggests that we either need to fix this or mark HHVM tests are allow-failure.

**Comment by davedevelopment** [comment]
Sorry, didn't even think about the coverage reports etc

**Comment by padraic** [comment]
@aik099 I'll look at the HHVM reports later. I also did some checking and it looks like HHVM pins to specific Mockery version for its framework testing. I might be reading it wrong but they are pinned to 0.9.2. Anyways, if we can fix them, I will though at some point HHVM can get its own stuff in order if a given fix is looking a bit nuts.

**Comment by fhinkel** [comment]
@padraic thank you!

**Comment by padraic** [comment]
Note: Master will now undo the trait include for code coverage for PHP 5.6 builds only using a small sed delete of that line.

**Pull request merged**
