### PR TITLE
No need to export some files and folders

### PR DESCRIPTION
**Pull request by lucasmichot**
No need to export some files and folders

### CODE REVIEW

**Comment by davedevelopment** [comment]
Is this something that people generally want? When I download a release tarball, I like that these things are there...

**Comment by lucasmichot** [comment]
I supposed that when people want to work on this package they usually either clone or either install it with `--prefer-dist` ?

**Comment by davedevelopment** [comment]
It's not necessarily about working on it for me, just generally.

That is, if I release a new version of Mockery, I'm releasing the code *and* everything that goes with it. 

I appreciate the "carbon footprint" effect of this, but I think that can be dealt with using proxies, like we do for a lot of things on the web. 

These type of changes have been made and then reverted on projects like Symfony and composer no longer recommends this type of thing in the docs.

**Comment by davedevelopment** [comment]
I'm going to close this, I prefer to have all of the info as part of the tarball.

**Comment by lichunqiang** [comment]
> I prefer to have all of the info as part of the tarball.

I agree, but I think should 'usefully' things. `tests` `travis` is useful for the user?

**Pull request closed without merging**
