### PR TITLE
Improved efficiency of HasKey matcher.

### PR DESCRIPTION
**Pull request by Bilge**

### CODE REVIEW

**Comment by davedevelopment** [comment]
I think this would have undesired effects when a key has a value of null?

**Comment by aik099** [comment]
You can use `array_key_exists` as well. In the past `isset` proved to be faster then `array_key_exists`, but performance tests done today doesn't confirm that anymore.

**Comment by Bilge** [comment]
@davedevelopment How so?

**Comment by davedevelopment** [comment]
``` php
$arr = [
    'some_key' => null,
];

var_dump(isset($arr['some_key'])); // bool(false)
```

**Comment by Bilge** [comment]
@davedevelopment Oops! Then I think we should use @aik099's suggestion.

**Comment by davedevelopment** [comment]
Thanks!

**Pull request merged**
