### PR TITLE
unused namespace removed

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by padraic** [comment]
Thanks @TomasVotruba !

**Comment by suwardany** [comment]
This is breaking the `EvalLoader`

```
Fatal error: Interface 'MockInterface' not found in ***/vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php(16) : eval()'d code on line 24
```

**Comment by GrahamCampbell** [comment]
#449

**Comment by TomasVotruba** [comment]
Would not be better to fix EvalLoader, so it doesn't require this custom behavior? It hidden feature.

**Pull request merged**
