### PR TITLE
Fix: __debugInfo for xdebug

### PR DESCRIPTION
**Pull request by fr05t1k**
For issue: https://github.com/padraic/mockery/issues/617

### CODE REVIEW

**Comment by davedevelopment** [comment]
I think it would be better to add `__debugInfo` to the list of [blacklisted methods](https://github.com/padraic/mockery/blob/master/library/Mockery/Generator/MockConfigurationBuilder.php#L26), that way people can still get their debugging info out of the mock as necessary. What do you think?

**Comment by fr05t1k** [comment]
@davedevelopment do you mean to add it to $blackListedMethods propperty as default? I think it will be great.

**Comment by fr05t1k** [comment]
@davedevelopment what do you think?

**Comment by davedevelopment** [comment]
Looks great, sorry for the delay, been on holiday.

Thanks!

**Pull request merged**
