### PR TITLE
#215 Original class destructor is called only when original construct…

### PR DESCRIPTION
**Pull request by davedevelopment**
…or was being called

This is a rebase of #218 and is related to #215 #355

### CODE REVIEW

**Comment by davedevelopment** [comment]
#215, #218 and #355 are pretty old issues that I (and others) have failed to come to a consensus on, so I'm just going to go ahead and merge this if nobody comes up with some strong objections today.

**Comment by davedevelopment** [comment]
I got impatient

**Comment by GrahamCampbell** [comment]
lol :)

**Comment by reinink** [comment]
I just ran into this issue when trying to mock the Mandrill API client library. I see this fix is tagged for version 1. Do you know of any work around to the problem in the meantime?

**Comment by davedevelopment** [comment]
@reinink this should get around it, but may have some side effects and probably isn't considered public API.

``` php
$mock = Mockery::mock(new \Mockery\Generator\MockConfiguration([MyThing::class]));
```

**Comment by reinink** [comment]
@davedevelopment Hey thanks, but I've actually just used a recent dev-master version, which seems to be working well.

**Comment by sanderdg** [comment]
@davedevelopment I'm also ran into this issue today and your suggested fix doesn't seem to work for me:
`
$mandrill = Mockery::mock(new MockConfiguration([Mandrill::class]));
die(($mandrill instanceof Mandrill) ? 'It works' : 'It doesn\'t work');
`

**Comment by erikverheij** [comment]
@sanderdg, I ran in the same issue, also with setting up a test for Mandrill eheh 😄.

I managed to work around it by setting a fake curl handle which makes the original destructor work again.
```
$mandrillClientMock->ch = curl_init('http://www.some-dummy-url.com/');
```

**Pull request merged**
