### PR TITLE
Add support for void methods (PHP 7.1+)

### PR DESCRIPTION
**Pull request by lcobucci**

### CODE REVIEW

**Comment by lcobucci** [comment]
@davedevelopment maybe this coverage report should be generated using the latest PHP version instead...

**Comment by lcobucci** [comment]
@davedevelopment thanks for the quick merge!

I'm having an issue with this that the test didn't cover: `PHP Fatal error:  Cannot use 'void' as class name as it is reserved in /tmp/Mockeryrku7ol on line 1` so mockery is considering `void` as an unexisting class and it's trying to create it. Do you have any idea where can I fix that?

**Comment by davedevelopment** [comment]
Maybe this 4884c3a0?

**Comment by lcobucci** [comment]
The structure is quite different on `0.9` but I think I've found, thanks.
Sending a new PR now 😉

**Pull request merged**
