### PR TITLE
Bumped the branch alias for 1.0

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by davedevelopment** [comment]
:+1: from me, @padraic?

**Comment by padraic** [comment]
It's fine by me here, Dave.

**Comment by davedevelopment** [comment]
Thanks @GrahamCampbell

**Comment by padraic** [comment]
Grand. I updated the README reference to the alias also just now.

**Comment by GrahamCampbell** [comment]
:rocket:

**Pull request merged**
