### PR TITLE
Fix `1.6.8` release

### LINKED ISSUE #1394: Latest release totally broken
### Mockery Version

1.6.8

### PHP Version

PHP 8.2

### Issue Description

Latest release of Mockery morning severely breaks Laravel test suite. Wouldn't expect this on a patch release. Can it be reverted?

https://github.com/laravel/framework/actions/runs/8249377959/job/22561635869

### Steps to Reproduce

_No response_

### Expected Behavior

_No response_

### Actual Behavior

_No response_

### Exception or Error

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ghostwriter**
This patch fixes an issue in the `1.6.8` release.

To test it out, you can include the following in your `composer.json`:

```
"require": {
    "mockery/mockery": "dev-fix/1.6.8-release"
}
```
And then run `composer update` to fetch the latest changes from the `fix/1.6.8-release` branch.

### CODE REVIEW

**Comment by ghostwriter** [comment]
Hey @mfn,

First, thank you.

Your willingness to offer your expertise and assistance is invaluable.

Branch `fix/1.6.8-release` is ready for testing, at your leisure.

Looking forward to your feedback, have a great weekend!

**Comment by mfn** [comment]
I can confirm that `composer require --dev mockery/mockery:dev-fix/1.6.8-release` runs through our private test suite without issues 🎉 

I see the pace of changes really goes strong, this is really very much appreciated! As much as phpunit itself is vital, Mockery is such an important cornerstone, thank you (et al?) 🙏🏼 

Out of curiosity, and since I'm not into the mockery development: can you say what it was? The amount of changes for "that one" release seemed staggering 😅

**Comment by ghostwriter** [comment]
That’s Great! 😎

Regarding the recent changes in Mockery,

I went through every file in the codebase and performed a thorough refactoring to improve performance and readability without altering the functionality.

- Removed a significant number of `is_*` function calls, dead cod, and unnecessary checks and loops, which helped streamline the code execution.

- Updated the codebase to adopt "modern” syntax, such as replacing `get_class` with `::class`, using null coalescing operator, cache function calls, improved strict equality checks and type checks, general CS Fixes,  etc.

---

In the process, I [forgot to prefix one of the class properties](https://github.com/mockery/mockery/pull/1396/commits/2b82b3cb194633f7bb45043c353dee34a5bc62bb) with `_mockery_` and [misplaced an if statement](https://github.com/mockery/mockery/pull/1396/commits/732245e6948b9986d2a0ccd90897e964c30f732c)

---

The goal for the 1.6.x branch is to make it as fast and clean as possible and mark the branch as `bug fix only`.

This sets the stage for subsequent updates:

I'm currently working on merging these improvements into the 2.0.x branch,
bumping the PHP version to 8.2, bump the PHPUnit version to 11 and introduce features like mocking readonly classes.

Preparing `ghostwriter/mockery-rector` to assist with refactoring.

I hope this provides some insight into the recent changes and the direction we're heading with Mockery.

Thanks again for testing this and for your kind words!

**Comment by mfn** [comment]
Awesome, very much appreciated 🙇🏼

**Pull request merged**
