### PR TITLE
Added styleci config to set the psr2 preset

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
NB, a leading slash should not be included when not required. It's a common mistake people make.

**Comment by padraic** [comment]
Travis CI build restarted. @GrahamCampbell pipped me to reverted a bad merge.

**Comment by GrahamCampbell** [comment]
I'll rebase this, one sec...

**Comment by GrahamCampbell** [comment]
I'm seeing green stuff. :)

**Comment by padraic** [comment]
@GrahamCampbell You're imagining things. ;)

**Comment by padraic** [comment]
All the green bits went away and now there's a big green button? Should I press it?

**Comment by padraic** [comment]
Better move the mouse pointer very carefully away from the Revert button...

**Comment by GrahamCampbell** [comment]
lol

**Comment by padraic** [comment]
Whoa. No laughing! This here is serious coding business. Those buttons do things.

**Pull request merged**
